### ISSUE TITLE
Can't add a tenant in the extension

### ISSUE THREAD

**Issue by wilfil** [yannick-beot-sp/vscode-sailpoint-identitynow#51]
**Describe the bug**
In a fresh clean installation of both VSCode and the extension, I'm not able to add a new tenant. 

**To Reproduce**
VSCode version: 1.83.0
Extension Version: 0.0.20

try to add a tenant, and it fails.

**Expected behavior**
The tenant should be added, but it's not.

**Error message**

"Error running command vscode-sailpoint-identitynow.add-tenant: command 'vscode-sailpoint-identitynow.add-tenant' not found. This is likely caused by the extension that contributes vscode-sailpoint-identitynow.add-tenant."

**Comment by yannick-beot-sp** [comment]
I have pushed a new version.
Can you try again?

**Comment by wilfil** [comment]
Thanks for your quick response. 

The plugin version that I see is still the 0.0.20, nothing changed and the error persists.

**Comment by yannick-beot-sp** [comment]
Latest version is version 0.0.21.
In the extension tab, you can check for extension updates.
It may help force the upgrade.

Le ven. 6 oct. 2023 à 15:54, Wilson Leite ***@***.***> a
écrit :

**Comment by wilfil** [comment]
Sorry Sir, but this version is not available. I uninstalled everything and reinstalled, and the version 21 is not there. :) 

I'll wait more, maybe there's a delay, not sure. 

Thank you anyways. Merci!

**Comment by reinaldojss13** [comment]
I have the same problem.

**Comment by reinaldojss13** [comment]
Hello,

I'm very worried because I'm on some projects and I need to deliver some things and I can't use VSCode to finish them.

Do you have any predictions for a solution to this bug?

Thank you in advance for your help.

**Comment by reinaldojss13** [comment]
Thanks for your help.

**Comment by reinaldojss13** [comment]
Hi,
The tenants now is visible for me, but I can't to see any thing and I received this error: "Error: Request failed with status code 401"

**Comment by wilfil** [comment]
Yes, tenants appeared, but they're empty.

**Comment by yannick-beot-sp** [comment]
Can you try to remove and add them again? 401 would mean that the
authentication failed.
Also, can you open the developer tool and share the logs in the console log?

Le ven. 6 oct. 2023 à 18:11, Wilson Leite ***@***.***> a
écrit :

**Comment by yannick-beot-sp** [comment]
Can you try to use the extension provided in https://github.com/yannick-beot-sp/vscode-sailpoint-identitynow/issues/50#issuecomment-1743396782?
You will need to change the extension of the file from .zip to .vsix before installing it.

**Comment by reinaldojss13** [comment]
I did this but still got the same error. "Error: Request failed with status code 401"

**Comment by yannick-beot-sp** [comment]
I could not reproduce these errors.
The latest version (0.0.22) add a lot of log to HTTP Request.
Please share your logs

**Comment by wilfil** [comment]
Couldn't find the logs. I searched the path C:\Program Files\Microsoft VS Code\resources\app\extensions, but nothing related to IDN there. Where should I look for? Thank you for your support! :)

**Comment by yannick-beot-sp** [comment]
Go to Help > Toggle Developer Tools.
The logs appears in the "Console" tab.

**Comment by reinaldojss13** [comment]
![image](https://github.com/yannick-beot-sp/vscode-sailpoint-identitynow/assets/35307794/51cd39b0-f572-445c-a1a6-11b5c8d080bb)

It's the log.

**Comment by wilfil** [comment]
![image](https://github.com/yannick-beot-sp/vscode-sailpoint-identitynow/assets/23223262/9a3c2a44-e381-44bc-a9f8-37e6b6ad3f2c)

**Comment by wilfil** [comment]
Authenticatin succeeds, but after that not.

**Comment by reinaldojss13** [comment]
I removed the tenant, and added it again and it worked correctly.

Thanks a lot for the help.

**Comment by wilfil** [comment]
I did the same, tried to remove/add the tenant, but unfortunately, the 400 error persists as per the logs above.

**Comment by wilfil** [comment]
![image](https://github.com/yannick-beot-sp/vscode-sailpoint-identitynow/assets/23223262/1ca3a4b9-b208-468a-a078-36c3f28402f2)

**Comment by yannick-beot-sp** [comment]
@wilfil 
It is really really weird.
Can you confirm me that you have this error when you are trying to add a tenant? If yes, it means it is when trying to get an access token and thus validate URL, client id and client secret.
Can you try again and give me the line above the error?
In 0.0.23, I now trace request and response/or error

**Comment by wilfil** [comment]
Hi @yannick-beot-sp , I can add the tenant since the version .21, but when I click on transforms, Workflows, Rules.. that's where I see the error 400. It means the authentication is okay, and it finds the tenant correctly.

**Comment by yannick-beot-sp** [comment]
That's incredibly weird as listing sources,  rules or else is just a GET.
So the request cannot be malformed per se...
I really need the request and response traces.

Le mer. 11 oct. 2023 à 23:27, Wilson Leite ***@***.***> a
écrit :
